export type { TinaTemplate } from 'tinacms'
export type { PageProps } from './types'
export type { Root } from './shared-kernel'
export { default } from './with'
export { default as schema, createSchema } from '../.tina/schema'
