import type { ResourceItemMap } from '../types'

export const resources = {
  'content/posts/0th-post.mdx': {
    id: 'content/posts/0th-post.mdx',
    filename: '0th-post',
    path: 'content/posts/0th-post.mdx',
    slug: '0th-post',
    resource: 'post',
    relativePath: '0th-post.mdx',
    data: {},
  },
  'content/posts/1th-post.mdx': {
    id: 'content/posts/1th-post.mdx',
    filename: '1th-post',
    path: 'content/posts/1th-post.mdx',
    slug: '1th-post',
    resource: 'post',
    relativePath: '1th-post.mdx',
    data: {},
  },
  'content/posts/2th-post.mdx': {
    id: 'content/posts/2th-post.mdx',
    filename: '2th-post',
    path: 'content/posts/2th-post.mdx',
    slug: '2th-post',
    resource: 'post',
    relativePath: '2th-post.mdx',
    data: {},
  },
  'content/posts/3th-post.mdx': {
    id: 'content/posts/3th-post.mdx',
    filename: '3th-post',
    path: 'content/posts/3th-post.mdx',
    slug: '3th-post',
    resource: 'post',
    relativePath: '3th-post.mdx',
    data: {},
  },
  'content/posts/4th-post.mdx': {
    id: 'content/posts/4th-post.mdx',
    filename: '4th-post',
    path: 'content/posts/4th-post.mdx',
    slug: '4th-post',
    resource: 'post',
    relativePath: '4th-post.mdx',
    data: {},
  },
  'content/posts/5th-post.mdx': {
    id: 'content/posts/5th-post.mdx',
    filename: '5th-post',
    path: 'content/posts/5th-post.mdx',
    slug: '5th-post',
    resource: 'post',
    relativePath: '5th-post.mdx',
    data: {},
  },
  'content/posts/6th-post.mdx': {
    id: 'content/posts/6th-post.mdx',
    filename: '6th-post',
    path: 'content/posts/6th-post.mdx',
    slug: '6th-post',
    resource: 'post',
    relativePath: '6th-post.mdx',
    data: {},
  },
  'content/posts/7th-post.mdx': {
    id: 'content/posts/7th-post.mdx',
    filename: '7th-post',
    path: 'content/posts/7th-post.mdx',
    slug: '7th-post',
    resource: 'post',
    relativePath: '7th-post.mdx',
    data: {},
  },
  'content/posts/8th-post.mdx': {
    id: 'content/posts/8th-post.mdx',
    filename: '8th-post',
    path: 'content/posts/8th-post.mdx',
    slug: '8th-post',
    resource: 'post',
    relativePath: '8th-post.mdx',
    data: {},
  },
  'content/posts/9th-post.mdx': {
    id: 'content/posts/9th-post.mdx',
    filename: '9th-post',
    path: 'content/posts/9th-post.mdx',
    slug: '9th-post',
    resource: 'post',
    relativePath: '9th-post.mdx',
    data: {},
  },
  'content/pages/home.md': {
    id: 'content/pages/home.md',
    filename: 'home',
    path: 'content/pages/home.md',
    slug: 'home',
    resource: 'page',
    relativePath: 'home.md',
    data: {},
  },
  'content/pages/about.md': {
    id: 'content/pages/about.md',
    filename: 'about',
    path: 'content/pages/about.md',
    slug: 'about',
    resource: 'page',
    relativePath: 'about.md',
    data: {},
  },
  'content/pages/portfolio.md': {
    id: 'content/pages/portfolio.md',
    filename: 'portfolio',
    path: 'content/pages/portfolio.md',
    slug: 'portfolio',
    resource: 'page',
    relativePath: 'portfolio.md',
    data: {},
  },
  'content/authors/napolean.md': {
    id: 'content/authors/napolean.md',
    filename: 'napolean',
    path: 'content/authors/napolean.md',
    slug: 'napolean',
    resource: 'author',
    relativePath: 'napolean.md',
    data: {},
  },
  'content/authors/pedro.md': {
    id: 'content/authors/pedro.md',
    filename: 'pedro',
    path: 'content/authors/pedro.md',
    slug: 'pedro',
    resource: 'author',
    relativePath: 'pedro.md',
    data: {},
  },
} as ResourceItemMap
