fragment ConfigParts on Config {
  darkMode
}

fragment PageParts on Page {
  title
  body
}

fragment PostParts on Post {
  title
  heroImg
  excerpt
  authors {
    __typename
    author {
      ... on Document {
        id
      }
    }
  }
  tags {
    __typename
    tag {
      ... on Document {
        id
      }
    }
  }
  date
  body
}

fragment AuthorParts on Author {
  name
}

fragment TagParts on Tag {
  name
}
